[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "NODE_OPTIONS='--max-old-space-size=2048' node .next/standalone/server.js"

[variables]
HOSTNAME = "0.0.0.0"
NODE_ENV = "production"
PORT = "8080"
