import { NextRequest, NextResponse } from 'next/server'

/**
 * Daily story cron — DISABLED.
 * Episodes are now event-driven: generated by the scenario monitor when a scenario triggers,
 * or manually by the user clicking "Begin the Story" / "Begin New Season".
 */
export async function GET(req: NextRequest) {
    const rawSecret = process.env.CRON_SECRET || ''
    const secret = rawSecret.trim()
    const authHeader = req.headers.get('authorization')
    const queryKey = req.nextUrl.searchParams.get('key')
    const expectedSecret = `Bearer ${secret}`
    const normalizedQueryKey = queryKey?.trim().replace(/ /g, '+')

    const isAuthorized =
        (authHeader && authHeader.trim() === expectedSecret) ||
        (normalizedQueryKey === secret)

    if (!isAuthorized) {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    return NextResponse.json({
        message: 'Retired — episodes are now event-driven (scenario monitor + manual).',
        processed: 0,
    })
}
